backchannel/config/routes.rb
Backchannel::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up", to: "users#new", as: "sign_up"
  get "/posts/up_vote/:id", to: "posts#up_vote", as: "up_vote_post"
  get "/posts/:post_id/new_comment/", to: "posts#new_comment", as: "new_comment"
  post "/posts/:post_id/create_comment/", to: "posts#create_comment", as: "create_comment"
  root to: "users#new"
  resources :posts
  resources :users
  resources :sessions
  resources :categories
end

backchannel/app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :presence => true
  validates :message, :presence => true

  has_many :votes
  belongs_to :user
  belongs_to :category
end

backchannel/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  attr_accessor :category_list
  before_filter :get_post, only: [:show, :update, :edit, :destroy]
  before_filter :get_category, only: [:create]
  before_filter :get_category_list, only: [:new]
  before_filter :check_logged_in, :only => [:new, :create, :edit, :update, :destroy, :up_vote, :new_comment, :create_comment]
  before_filter :check_owns, :only => [:edit, :update]
  before_filter :check_owns_or_admin, :only => [:destroy]
  

  def new
    if logged_in?
      @post = Post.new
    end
  end

  def create
    @post = Post.new(post_params.except(:category))
    #@post.category_id = Category.where(:name => post_params[:category])
    @post.category_id = @category.id
    @post.user_id = session[:user_id]
    @post.save
    flash[:notice] = "Post created!"
    redirect_to @post
  end

  def show
    @user_name = User.find(@post.user_id).user_name
    @category_name = Category.find(@post.category_id).name
    @comments = Comment.where(post_id: @post.id)
  end

  def index
    @posts = Post.all
  end

  def edit
  end

  def update
    @post.update(post_params)
    if @post.save == false
      flash[:error] = "Failed up save post update!"
    else
      flash[:notice] = "Post updated!"
    end
    redirect_to posts_path
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def up_vote
    @post_id = params[:id]
    @user_id = session[:user_id]
    if Vote.exists?(post_id: @post_id, user_id: @user_id)
      flash[:error] = "You've already voted for this post!"
      redirect_to posts_path
      return
    end

    if Post.find(@post_id).user_id == @user_id
      flash[:error] = "You can't vote for your own post!"
      redirect_to posts_path
      return
    end

    vote = Vote.new(post_id: @post_id, user_id: @user_id)
    if vote.save
      flash[:notice] = "Vote for post counted!"
    else
      flash[:error] = "Unable to save vote!"
    end
    redirect_to posts_path
  end

  def new_comment
    if logged_in?
      @comment = Comment.new
    end
  end

  def create_comment
    #@comment = Comment.new(post_id: params[:post_id], message: params["message"])
    @comment = Comment.new
    @comment.post_id = params[:post_id]
    @comment.message = params[:comment][:message]
    @comment.user_id = session[:user_id]
    if @comment.save
      flash[:notice] = "Commented!"
    else
      flash[:error] = "Unable to save comment!"
    end
    redirect_to Post.find(params[:post_id])
  end


  private

  def post_params
    params.require(:post).permit(:title, :message, :category)
  end

  def get_post
    @post = Post.find(params[:id])
  end

  def get_category
    if Category.where(:name => post_params[:category]).empty?
      @category = nil
    else
      @category = Category.where(:name => post_params[:category])[0]
    end
  end

  def get_category_list
    @category_list = []
    Category.where(:status => "approved").each do |category|
      @category_list << [category.name.capitalize, category.name]
    end
  end

  def check_owns
    if session[:user_id] != @post.user_id
      flash[:error] = "You can only edit your own posts!"
      redirect_to posts_path
    end
  end

  def logged_in?
    session[:user_id] != nil
  end

  def check_logged_in
    if session[:user_id].nil?
      flash[:error] = "Must be logged in!"
      redirect_to posts_path
    end
  end

  def check_owns_or_admin
    if session[:user_id] != @post.user_id and User.find(session[:user_id]).rights == "user"
      flash[:error] = "You can only edit your own posts!"
      redirect_to posts_path
    end
  end

end

backchannel/app/helpers/posts_helper.rb
module PostsHelper
end

backchannel/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for :post, url: post_path, html: {method: :put} do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

backchannel/app/views/posts/index.html.erb
<h1>Post List</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Votes</th>
    <th>Comments</th>
    <th>Category</th>
    <th>User</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

  <% @posts.each do |post| %>
    <tr>
      <td><%= link_to post.title, post_path(post) %></td>
      <td><%= Vote.where(:post_id => post.id).count %></td>
      <td><%= Comment.where(:post_id => post.id).count %></td>
      <td><%= Category.exists?(post.category_id) ? Category.find(post.category_id).name : "No such category! "%></td>
      <td><%= User.exists?(post.user_id) ? User.find(post.user_id).user_name : "No such user!"  %></td>
      <td><%= link_to "Edit", edit_post_path(post)  %></td>
      <td><%= link_to "Delete", post_path(post), :method => :delete %></td>
    <tr>
  <% end %>
</table>

<p><%= link_to "New Post", new_post_path %></p>

backchannel/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for :post, url: posts_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </p>

  <p>
    <%= f.label :category %><br>
    <% if @category_list == nil or @category_list == []%>
      <i>No categories!</i>
    <% else %>
      <%= f.select :category, @category_list %>
    <% end %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

backchannel/app/views/posts/new_comment.html.erb
<h1>New Comment:</h1>

<%= form_for :comment, url: create_comment_path do |f| %>
  <p>
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

backchannel/app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Category:</strong>
  <%= @category_name %>
</p>

<p>
  <strong>Votes:</strong>
  <%= Vote.where(:post_id => @post.id).count %>
</p>

<p>
  <strong>By:</strong>
  <%= @user_name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @post.message %>
</p>

<p>
  <strong>Comments:</strong>
  <% if @comments.count == 0 %>
    No comments! Be the first via the link below.
  <% else %>
    <% @comments.each do |comment| %>
      <br /><br />
      <tr>
        <td>By: <%= User.exists?(comment.user_id) ? User.find(comment.user_id).user_name : "No such user!"  %></td><br />
        <td>Message: <%= comment.message  %></td>
      <tr>
    <% end %>
  <% end %>
</p>


<p>
  <%= link_to "Up Vote", up_vote_post_path(@post.id) %>
  <%= link_to "Comment", new_comment_path(@post.id) %>
  <%= link_to "Edit", edit_post_path %>
  <%= link_to "Delete", post_path, :method => :delete  %>
  <%= link_to "New", new_post_path %>
  <%= link_to "Post list", posts_path %>
</p>