backchannel/config/routes.rb
Backchannel::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up", to: "users#new", as: "sign_up"
  get "/posts/up_vote/:id", to: "posts#up_vote", as: "up_vote_post"
  get "/posts/:post_id/new_comment/", to: "posts#new_comment", as: "new_comment"
  post "/posts/:post_id/create_comment/", to: "posts#create_comment", as: "create_comment"
  root to: "users#new"
  resources :posts
  resources :users
  resources :sessions
  resources :categories
end

backchannel/app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :status, :presence => true

  has_many :posts
end

backchannel/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :get_category, only: [:edit, :destroy, :update, :show]
  before_filter :check_logged_in, only: [:edit, :destroy, :update, :create]
  before_filter :check_admin, only: [:edit, :destroy, :update]

  def new
  end

  def show
  end

  def create
    if category_exists?
      flash[:error] = "Category aleady exists!"
    else
      @category = Category.new(category_params)
      if !admin?
        @category.status = "pending"
      else
        @category.status = "approved"
      end
      if @category.save
        flash[:notice] = "Category proposed!"
      else
        flash[:notice] = "Unable to save category for unknown reason! :("
      end
    end
    redirect_to categories_path
  end

  def index
    @categories = Category.all
  end

  def edit
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  def update
    @category.update(category_params)
    if @category.save == false
      flash[:error] = "Failed up save category update."
    else
      flash[:notice] = "Category updated!"
    end
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :status)
  end

  def get_category
    @category = Category.find(params[:id])
  end

  def category_exists?
    Category.exists?(category_params)
  end

  def admin? 
    if User.find(session[:user_id]).rights != "user"
      true
    else
      false
    end
  end

  def check_admin
    if !admin?
      flash[:error] = "You must be an admin to approve/reject categories!"
      redirect_to categories_path
      return
    end
  end

  def check_logged_in
    if !User.exists?(session[:user_id])
      flash[:error] = "You must be logged in!"
      redirect_to categories_path
      return
    end
  end

end

backchannel/app/helpers/categories_helper.rb
module CategoriesHelper
end

backchannel/app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= form_for :category, url: category_path, html: {method: :put} do |f| %>
  <p>
    <%= f.label "Name of Category" %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :status%><br>
    <%= f.select :status, [["Pending", "pending"], ["Approved", "approved"]] %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

backchannel/app/views/categories/index.html.erb
<h1>Categories List</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

  <% @categories.each do |category| %>
    <tr>
      <td><%= link_to category.name, category_path(category) %></td>
      <td><%= category.status%></td>
      <td><%= link_to "Edit", edit_category_path(category)  %></td>
      <td><%= link_to "Delete", category_path(category), :method => :delete %></td>
    <tr>
  <% end %>
</table>

<p><%= link_to "New Category", new_category_path %></p>

backchannel/app/views/categories/new.html.erb
<h1>Propose Category</h1>

Your category will need to be approved by an admin.

<%= form_for :category, url: categories_path do |f| %>
  <p>
    <%= f.label "Name of Category" %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit "Propose Category" %>
  </p>
<% end %>

<%= link_to "Category list", categories_path %>

backchannel/app/views/categories/show.html.erb
<p>
  <strong>Category Name:</strong>
  <%= @category.name %>
</p>
 
<p>
  <strong>Status:</strong>
  <%= @category.status %>
</p>

<p>
  <%= link_to "Edit", edit_category_path %>
  <%= link_to "Delete", category_path, :method => :delete  %>
  <%= link_to "New", new_category_path %>
  <%= link_to "Categories list", categories_path %>
</p>