backchannel/config/routes.rb
Backchannel::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up", to: "users#new", as: "sign_up"
  get "/posts/up_vote/:id", to: "posts#up_vote", as: "up_vote_post"
  get "/posts/:post_id/new_comment/", to: "posts#new_comment", as: "new_comment"
  post "/posts/:post_id/create_comment/", to: "posts#create_comment", as: "create_comment"
  root to: "users#new"
  resources :posts
  resources :users
  resources :sessions
  resources :categories
end

backchannel/app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessor :password, :password_confirmation
  has_secure_password
  validates_presence_of :email
  validates_uniqueness_of :email
  validates :user_name, :presence => true
  validates :rights, :presence => true

  has_many :votes
  has_many :posts
end

backchannel/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :get_user, only: [:show, :update, :edit, :destroy]
  before_filter :check_logged_in, only: [:edit, :update, :destroy]
  before_filter :check_owns_or_privileged, only: [:edit, :update, :destroy]
  before_filter :check_not_super, only: [:destroy]
  before_filter :check_not_admin_on_admin, only: [:destroy, :edit]

  def new
    if first_user?
      flash[:notice] = "Welcome to your new app! Create your Super Admin!"
    end
    @user = User.new
  end

  def create
    if first_user?
      handle_first_user
      return
    end

    if modifying_super?
      flash[:error] = "There can only be one Super Admin!"
      redirect_to sign_up_path
      return
    end
      
    if is_logged_out? and modifying_admin?
      flash[:error] = "You can't create an admin, who are you?!"
      redirect_to sign_up_path
      return
    end

    if my_rights == "user" and modifying_admin?
      flash[:error] = "You can't create an admin/super, you're a user!"
      redirect_to sign_up_path
      return
    end

    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Signed up!"
      redirect_to log_in_path
    else
      render "new"
    end
  end

  def show
    if is_logged_out?
      flash[:error] = "You can view credentials! Who are you!?"
      @user = nil
      redirect_to users_path
      return
    end

    if my_rights == "user" and !owns?
      flash[:error] = "Users can't view other user's credentials!"
      @user = nil
      redirect_to users_path
      return
    end

    if my_rights == "admin" and @user.rights != "user" and !owns?
      flash[:error] = "You can only edit user/your credentials!"
      @user = nil
      redirect_to users_path
      return
    end

    if my_rights != "super" and @user.rights == "super"
      flash[:error] = "Only the Super Admin can view their data!"
      @user = nil
      redirect_to users_path
    end
  end

  def index
    @users = User.all
  end

  def edit
  end

  def update
    if @user.rights == "super" and user_params[:rights] != "super"
      flash[:error] = "You can't demote the Super Admin!"
      redirect_to users_path
      return
    end

    @user.update(user_params)
    if @user.save
      flash[:notice] = "User updated!"
    else
      flash[:error] = "Failed up save user update."
    end
    redirect_to users_path
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def login
  end

  private

  def user_params
    params.require(:user).permit(:email, :user_name, :password, :rights, :id, :password_confirmation, :password_digest)
  end

  def first_user?
    User.count == 0
  end

  def handle_first_user
    @user = User.new(user_params)
    flash[:notice] = "You're the first user! You were upgraded to Super Admin!"
    @user.rights = "super"
    if @user.save
      redirect_to root_url
    #else
    #  render "new"
    end
  end
    
  # Helpers for checking the rights of the user being edited
  def modifying_user?; user_params[:rights] == "user"; end
  def modifying_admin?; user_params[:rights] == "admin"; end
  def modifying_super?; user_params[:rights] == "super"; end

  # Helpers for checking the rights of the user we're serving
  def is_logged_out?; session[:user_id] == nil; end
  #def is_user?; session[:user_id] == "user"; end
  #def is_admin?; session[:user_id] == "admin"; end
  #def is_super?; session[:user_id] == "super"; end

  def my_rights
    if is_logged_out?
      return nil
    end
    User.find(session[:user_id]).rights
  end

  def get_user
    @user = User.find(params[:id])
  end

  def owns?
    session[:user_id] == @user.id
  end

  def check_owns_or_privileged
    if session[:user_id] != @user.id and my_rights == "user"
      flash[:error] = "You can only edit your own account!"
      redirect_to users_path
      return
    end
  end

  def check_logged_in
    if session[:user_id].nil?
      flash[:error] = "You must be logged in!"
      redirect_to users_path
    end
  end

  def check_not_super
    if @user.rights == "super"
      flash[:error] = "You can't delete the Super Admin!"
      redirect_to users_path
    end
  end

  def check_not_admin_on_admin
    if @user.rights != "user" and User.find(session[:user_id]).rights == "admin" and session[:user_id] != @user.id
      flash[:error] = "Admins can't edit other admin's data!"
      redirect_to users_path
    end
  end
end

backchannel/app/helpers/users_helper.rb
module UsersHelper
end

backchannel/app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for :user, url: user_path, html: {method: :put} do |f| %>
  <p>
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.label :rights %><br>
    <%= f.select :rights, [["User", "user"], ["Admin", "admin"], ["Super Admin", "super"]] %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

backchannel/app/views/users/index.html.erb
<h1>User List</h1>

<table>
  <tr>
    <th>User name</th>
    <th>Email</th>
    <th>Rights</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.user_name, user_path(user) %></td>
      <td><%= user.email %></td>
      <td><%= user.rights %></td>
      <td><%= link_to "Edit", edit_user_path(user)  %></td>
      <td><%= link_to "Delete", user_path(user), :method => :delete %></td>
    <tr>
  <% end %>
</table>

<p><%= link_to "New User", new_user_path %></p>

backchannel/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.label :rights %><br>
    <%= f.select :rights, [["User", "user"], ["Admin", "admin"], ["Super Admin", "super"]] %>
  </p>

  <p class="button"><%= f.submit %></p>
<% end %>

backchannel/app/views/users/show.html.erb
<p>
  <strong>User name:</strong>
    <%= @user.user_name %>
</p>

<p>
  <strong>Email:</strong>
    <%= @user.email %>
</p>

<p>
  <strong>Rights:</strong>
    <%= @user.rights %>
</p>

<p>
  <%= link_to "Edit", edit_user_path %>
  <%= link_to "Delete", user_path, :method => :delete  %>
  <%= link_to "User list", users_path %>
</p>